# Generated by Django 4.2.27 on 2025-12-30 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
