# Generated by Django 4.2.27 on 2026-01-01 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_price_remove_product_stock'),
        ('orders', '0004_order_address_line_order_city_order_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default='UNKNOWN', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size_ml',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.productvariant'),
        ),
    ]
